{{- if or (eq .Values.upbound.controlPlane.permission "view") (eq .Values.upbound.controlPlane.permission "edit") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "crossplane.name" . }}-view
  labels:
    {{- include "labelsAgent" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "crossplane.name" . }}-view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: upbound:view
{{- if eq .Values.upbound.controlPlane.permission "edit" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "crossplane.name" . }}-edit
  labels:
    {{- include "labelsAgent" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "crossplane.name" . }}-edit
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: upbound:edit
{{- end }}
{{- end }}